#!/usr/bin/env python3
"""Generate GitHub Actions step summary."""

import json
import os
from datetime import datetime
from pathlib import Path


def main():
    lines = ["## 🐴 Race Report Summary\n"]

    # Run info
    lines.append(f"**Generated:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}")
    lines.append(f"**Run:** #{os.environ.get('GITHUB_RUN_NUMBER', 'N/A')}")
    lines.append("")

    # Results
    if Path("qualified_races.json").exists():
        try:
            with open("qualified_races.json") as f:
                data = json.load(f)
            races = data.get("races", [])

            lines.append("### 📊 Results\n")
            lines.append(f"**Qualified Races:** {len(races)}")

            if races:
                venues = {}
                for race in races:
                    v = race.get("venue", "Unknown")
                    venues[v] = venues.get(v, 0) + 1

                lines.append(f"**Venues:** {len(venues)}")
                lines.append("")
                lines.append("| Venue | Races |")
                lines.append("|-------|-------|")
                for v, c in sorted(venues.items(), key=lambda x: -x[1])[:10]:
                    lines.append(f"| {v} | {c} |")
        except Exception as e:
            lines.append(f"⚠️ Error: {e}")
    else:
        lines.append("### ⚠️ No Results\n")
        lines.append("No qualified races file generated.")

    lines.append("")

    # Browser verification
    if Path("browser_verification.json").exists():
        try:
            with open("browser_verification.json") as f:
                data = json.load(f)
            lines.append("### 🌐 Browser Status\n")
            for name, result in data.get("tests", {}).items():
                status = "✅" if result.get("passed") else "❌"
                lines.append(f"- {status} {name}")
        except:
            pass

    lines.append("\n---")
    lines.append("*Generated by Fortuna Race Pipeline*")

    print("\n".join(lines))


if __name__ == "__main__":
    main()
