# scripts/generate_spec_ultimate.py
import os
import sys
import subprocess
from pathlib import Path

def main():
    """
    Generates a PyInstaller spec file for the "Ultimate" workflow,
    ensures __init__.py files exist, and runs the PyInstaller build.
    """
    print("--- 🐍 Ultimate Spec Generator ---")

    # 1. Get environment variables
    try:
        bk_dir = os.environ['BACKEND_DIR']
        mod_path = os.environ['MODULE_PATH']
        frontend_out = os.environ['FRONTEND_OUT']
        entry = f"{bk_dir}/main.py"
    except KeyError as e:
        print(f"❌ Missing environment variable: {e}")
        sys.exit(1)

    print(f"Backend Dir: {bk_dir}")
    print(f"Module Path: {mod_path}")
    print(f"Frontend Out: {frontend_out}")
    print(f"Entry Point: {entry}")

    # 2. Validate paths
    if not Path(entry).exists():
        print(f"❌ Entry point not found: {entry}")
        sys.exit(1)
    if not Path(frontend_out).exists():
        print(f"❌ Frontend output directory not found: {frontend_out}")
        sys.exit(1)

    # 3. Ensure __init__.py files exist for all potential packages
    # This covers both 'web_service' and 'python_service' structures.
    inits = [
        "web_service/__init__.py",
        "web_service/backend/__init__.py",
        "python_service/__init__.py"
    ]

    pure_injections = []
    print("--- Ensuring package __init__.py files ---")
    for p in inits:
        path = Path(p)
        # Only create if the parent directory exists. This prevents creating
        # 'python_service' when we're in 'web_service' mode, and vice-versa.
        if path.parent.exists():
            if not path.exists():
                print(f"   - Creating missing: {path}")
                path.write_text("# HatTrick Injection")
            else:
                print(f"   - Found existing: {path}")

            # Convert path to module name (e.g., 'web_service/backend' -> 'web_service.backend')
            mod_name = str(path.parent).replace(os.sep, '.')
            # Use absolute POSIX path for PyInstaller
            abs_path_posix = path.resolve().as_posix()
            pure_injections.append(f"('{mod_name}', '{abs_path_posix}', 'PYMODULE')")

    injection_str = ",\n    ".join(pure_injections)

    # 4. Define the spec file content
    spec_content = f"""
# -*- mode: python ; coding: utf-8 -*-
# Generated by scripts/generate_spec_ultimate.py

from PyInstaller.utils.hooks import collect_data_files, collect_submodules

block_cipher = None

# --- Analysis Phase ---
a = Analysis(
    ['{entry}'],
    pathex=[],
    binaries=[],
    datas=collect_data_files('uvicorn') + collect_data_files('slowapi') + [('{frontend_out}', 'ui')],
    hiddenimports=collect_submodules('{mod_path}'),
    hookspath=[],
    runtime_hooks=[],
    excludes=['tests', 'pytest'],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

# --- PURE Injection (Dynamic) ---
# This ensures that packages are correctly identified by PyInstaller.
a.pure += [
    {injection_str}
]

# --- PYZ (Python Archive) Phase ---
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

# --- EXE (Executable) Phase ---
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='fortuna-backend',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False  # GUI application
)
"""

    # 5. Write the spec file
    spec_path = "hat-trick.spec"
    print(f"--- Writing spec file to {spec_path} ---")
    with open(spec_path, "w", encoding="utf-8") as f:
        f.write(spec_content)
    print(f"✅ Spec file created.")
    print("-" * 20)
    print(spec_content)
    print("-" * 20)

    # 6. Run PyInstaller
    print("--- Running PyInstaller build ---")
    cmd = [
        sys.executable,  # Use the same python interpreter running this script
        "-m", "PyInstaller",
        spec_path,
        "--clean",
        "--noconfirm",
        "--log-level", "WARN"
    ]

    result = subprocess.run(cmd, capture_output=True, text=True)

    if result.returncode != 0:
        print("❌ PyInstaller build failed!")
        print("--- STDOUT ---")
        print(result.stdout)
        print("--- STDERR ---")
        print(result.stderr)
        sys.exit(1)

    print("✅ PyInstaller build successful.")
    print(result.stdout)


if __name__ == "__main__":
    main()
