# scripts/generate_spec_electron.py
import os
import sys
import subprocess
from pathlib import Path

def main():
    """
    Generates a PyInstaller spec file for the Electron workflows,
    ensures __init__.py files exist, and runs the PyInstaller build.
    """
    print("--- 🐍 Electron Spec Generator ---")

    # 1. Get environment variables
    try:
        bk_dir = os.environ['BACKEND_DIR']
        entry = f"{bk_dir}/main.py"
    except KeyError as e:
        print(f"❌ Missing environment variable: {e}")
        sys.exit(1)

    print(f"Backend Dir: {bk_dir}")
    print(f"Entry Point: {entry}")

    # 2. Validate paths
    if not Path(entry).exists():
        print(f"❌ Entry point not found: {entry}")
        sys.exit(1)

    # 3. This build is simpler and doesn't require the dynamic __init__
    # injection that the web service does, as it's a more controlled environment.
    # We just need to ensure the `python_service` is on the path.
    pathex = [str(Path.cwd().resolve())]
    print(f"Using pathex: {pathex}")


    # 4. Define the spec file content for Electron
    # This is based on the configuration required for the Electron app,
    # which excludes the web service components.
    spec_content = f"""
# -*- mode: python ; coding: utf-8 -*-
# Generated by scripts/generate_spec_electron.py

from PyInstaller.utils.hooks import collect_data_files

block_cipher = None

a = Analysis(
    ['{entry}'],
    pathex={pathex},
    binaries=[],
    datas=[],
    hiddenimports=[
        'uvicorn.lifespan', 'uvicorn.loops', 'uvicorn.protocols',
        'win32timezone',
        'win32serviceutil',
        'win32service',
        'win32event'
    ],
    hookspath=[],
    runtime_hooks=[],
    excludes=['web_service'], # Explicitly exclude the other backend
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='fortuna-backend',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True, # Electron requires a console app to manage stdio
)
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='fortuna-backend',
)
"""

    # 5. Write the spec file
    spec_path = "fortuna-backend-electron.spec"
    print(f"--- Writing spec file to {spec_path} ---")
    with open(spec_path, "w", encoding="utf-8") as f:
        f.write(spec_content)
    print(f"✅ Spec file created.")

    # 6. Run PyInstaller
    print("--- Running PyInstaller build ---")
    cmd = [
        sys.executable,
        "-m", "PyInstaller",
        spec_path,
        "--clean",
        "--noconfirm",
        "--log-level", "WARN"
    ]

    result = subprocess.run(cmd, capture_output=True, text=True)

    if result.returncode != 0:
        print("❌ PyInstaller build failed!")
        print("--- STDOUT ---")
        print(result.stdout)
        print("--- STDERR ---")
        print(result.stderr)
        sys.exit(1)

    print("✅ PyInstaller build successful.")
    print(result.stdout)

if __name__ == "__main__":
    main()
